name: Jest Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DEBUG_TEST_SETUP: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        continue-on-error: true # This is required to ignore unsupported platform errors due to the fsevents sub-dependency

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.36.2'

      - name: Run Jest tests
        run: npm test
