name: Test Coverage

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      DEBUG_TEST_SETUP: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --no-optional

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.36.2'

      - name: Run tests with coverage
        run: npm test -- --coverage
